defaults:
_target_: src.models.diffusion_condition_diffusion_model.ConditionDiffusionModel

denoise_net:
  _target_: src.models.unet.unet_condition.ConditionalUNet
  in_ch: 3 # the channel count of the input

n_train_steps: 1000 # the number of diffusion step
