_target_: src.models.condition_diffusion_module.ConditionDiffusionModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net: 
  _target_: src.models.diffusion.condition_diffusion_model.ConditionDiffusionModel
  timesteps: 1000
  denoise_net:
    _target_: src.models.unet.unet_condition.ConditionalUNet
    in_ch: 1

# /mnt/banana/student/ptrang/diffusion_model/src/models/unet/unet_condition.py
# compile model for faster training with pytorch 2.0
compile: false
