_target_: src.models.diffusion_module.DiffusionModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net: 
  _target_: src.models.diffusion.net.diffusion_model.DiffusionModel
  denoise_net:
    _target_: src.models.unet.unet.UNet
    in_ch: 1
  sampler:
    _target_: src.models.diffusion.sampler.ddim.DDIMSampler
    n_infer_steps: 1000
    n_train_steps: 1000


# compile model for faster training with pytorch 2.0
compile: false
